### ISSUE TITLE
Restrict to "beapi" user by default

### ISSUE THREAD

**Issue by herewithme** [BeAPI/bea-scm-infos#6]
The toolbar is already heavily used by other plugins in my opinion. Is it possible to display the info only for the "beapi" account?

In addition, is it possible to display the info basically in the footer, and / or near the version information of WP in the back office.

**Comment by ghost** [comment]
true for that, that's why you have a filter to make your own condition to display admin bar. Do you think we should set this by default anyway with a constant for example ?

I must admit I've deleted footer text filter... I could reinject this. I thought that was useless but it seems useful

**Comment by ghost** [comment]
Hi, https://github.com/BeAPI/bea-scm-infos/wiki/Tips-&-tricks see this https://github.com/BeAPI/bea-scm-infos/releases/tag/2.2
